language: java

# configure the Maven environment
before_install:
  - source <(curl -fsSL https://raw.github.com/daisy/maven-parents/travis-2/before_install)

# main task, run the verify goal
script: mvn verify

# if the build succeeds, deploy the artifact (tests are skipped)
after_success: 
  - source <(curl -fsSL https://raw.github.com/daisy/maven-parents/travis-2/after_success)

# if the build fails because of an integration test, print the logs
after_failure:
  - find . -type f -path '*/target/it/*/build.log' -execdir bash -c 'if ! cat build.log | grep -qFx "[INFO] BUILD SUCCESS"; then tail -250 build.log; fi' \;

# whitelist; only deploy master branch
branches:
  only:
  - master
  - /^super\/.+$/

env:
  global:
    - secure: "Vn2O8sDLSo+fNy4HKWJP4+qqkzCuCku0M8Ti6gOSFWoo/M3bI6Xp2GfeV4RHK7+qscV0DS9YHZTT50VkANQU0KJzjyxKZKoWajc00ToSafx7RmIf3cAiNhWPdsML/ucNvVIxhmlkXS2Wup7+530o+FEFS+hNbrpU4WcIgGX8rOk="
    - secure: "V9ygqgtZKSfoARVGyRz/wiOqqpXXdOVWTvuyecwUspF/g5HQKh/OiabXrKakmrnKi/JfIa2tezOAtbyP/DZWlRju7xubrKUHnMFgGS4UbtheHuqEOUmI6xzQgSAvmn2aitCwYH2T0GXIDPOHYC6imyIVR8hJuGwLovc1PKkkETE="
